### ISSUE TITLE
Adding device causes reboot to fail

### ISSUE THREAD

**Issue by Jacksonbm1** [OpenWonderLabs/homebridge-switchbot-ble#104]
**Describe The Bug:**

I installed the plugin and everything works fine. When I try to add a device and restart homebridge, it gets stuck and won't boot (logs below).

**To Reproduce:**

Install the plugin, add a bot.

**Expected behavior:**

Homebridge should boot

**Logs:**

```
TypeError: Cannot read property 'toLowerCase' of undefined
    at SwitchBotPlatform.accessories (/usr/lib/node_modules/@switchbot/homebridge-switchbot-ble/src/switchbot-platform.ts:73:79)
    at /usr/lib/node_modules/homebridge/src/bridgeService.ts:529:24
    at new Promise (<anonymous>)
    at BridgeService.loadPlatformAccessories (/usr/lib/node_modules/homebridge/src/bridgeService.ts:523:12)
    at /usr/lib/node_modules/homebridge/src/server.ts:445:42
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:159:29)
```

**Homebridge Config:**

```json

            "devices": [
                {
                    "type": "bot",
                    "name": "doorbell"
                }
            ],
            "name": "SwitchBotPlatform",
            "platform": "SwitchBotPlatform"

***Read and Paste over this Text the Text Above^^^^^^
```

**Screenshots:**

**Device Model:**

# **Environment:**

- **Node.js Version**: 
- **NPM Version**: 
- **Homebridge Version**: 
- **Homebridge SwitchBot BLE Plugin Version**:
- **Homebridge Config UI X Plugin Version**:
- **Operating System**:

**Comment by Jacksonbm1** [comment]
Resolved, I figured out that I had set up the config file wrong (figures). I didn't have the mac address right. Here's a link to how to find it: https://pypi.org/project/switchbot-mqtt/#:~:text=Use%20sudo%20hcitool%20lescan%20or,determine%20your%20SwitchBot's%20mac%20address.
