### ISSUE TITLE
Bot only works once

### ISSUE THREAD

**Issue by Jacksonbm1** [OpenWonderLabs/homebridge-switchbot-ble#105]
**Describe The Bug:**

Running the bot. I'll press the homekit tile and it will turn to "on." The switch will press inwards and retract (working as intended). However, after that, my homebridge freezes up (all devices set to not found), and I can't press anything for a bit until it resets itself.

**To Reproduce:**

Press the on button.

**Expected behavior:**

The switch should be able to be activated multiple times. I'm not sure if 'on/off' act as buttons irrespective of status (you can press on or off to have the bot push a button) or if the plugin automatically switches it back off once the switch is retracted. However, this isn't what should be happening

**Logs:**
```
[3/12/2021, 11:29:57 PM] [SwitchBotPlatform] Current state of Bot was returned: OFF
[3/12/2021, 11:30:02 PM] [SwitchBotPlatform] Target state of Bot setting: ON
[3/12/2021, 11:30:03 PM] [SwitchBotPlatform] Scan done.
[3/12/2021, 11:30:03 PM] [SwitchBotPlatform] WoHand (db:ee:1b:f9:f1:2a) was found.
[3/12/2021, 11:30:03 PM] [SwitchBotPlatform] Bot is running...
[3/12/2021, 11:30:04 PM] [SwitchBotPlatform] Error: Failed to discover services and characteristics: DISCONNECTED
    at SwitchbotDeviceWoHand._ondisconnect_internal (/usr/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/node-switchbot/lib/switchbot-device.js:161:16)
    at Peripheral.<anonymous> (/usr/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/node-switchbot/lib/switchbot-device.js:122:14)
    at Object.onceWrapper (events.js:421:28)
    at Peripheral.emit (events.js:315:20)
    at Noble.onDisconnect (/usr/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/@abandonware/noble/lib/noble.js:241:16)
    at NobleBindings.emit (events.js:315:20)
    at NobleBindings.onDisconnComplete (/usr/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:274:10)
    at Hci.emit (events.js:315:20)
    at Hci.onSocketData (/usr/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/@abandonware/noble/lib/hci-socket/hci.js:557:12)
    at BluetoothHciSocket.emit (events.js:315:20)
[3/12/2021, 11:30:04 PM] [SwitchBotPlatform] Bot state failed to be set to: ON
[3/12/2021, 11:32:10 PM] [SwitchBotPlatform] Current state of Bot was returned: OFF


```
Show the Homebridge logs here. If using Homebridge Config-UI-X, you can easly downlaod your log by visiting the log page on the UI and Clicking the Download Icon in the top right.
Remove any sensitive information, such as your homebridge-switchbot-ble device info.

Please Turn on Debug Mode before submitting your Issue so more logs can be shared to fix the issue being submitted.

There is a hidden `"devicediscovery: true"` option that you can add to your config that will output data about your device to your log also.

***Read and Paste over this Text the Text Above^^^^^^
```

**Homebridge Config:**

```json

        {
            "devices": [
                {
                    "type": "bot",
                    "name": "door",
                    "bleMac": <removed by user>
                }
            ],
            "name": "SwitchBotPlatform",
            "platform": "SwitchBotPlatform"
        }


***Read and Paste over this Text the Text Above^^^^^^
```

**Screenshots:**

**Device Model:**

Switchbot bot white

# **Environment:**

- **Node.js Version**: v14.16.0
- **NPM Version**: v6.14.11
- **Homebridge Version**: v1.3.3 (current)
- **Homebridge SwitchBot BLE Plugin Version**: v1.2.10 (current)
- **Homebridge Config UI X Plugin Version**: v4.40.0
- **Operating System**: Raspbian

**Comment by Jacksonbm1** [comment]
Resolved (sort of): The issue seems to be that the raspberry pi just doesn't have the bluetooth range to consistently connect with the switchbot bot. HOWEVER, I was able to find a solution. This might not be the best place to put it, but this plug in: https://github.com/zizi4n5/homebridge-switchbot-for-mac has a retry setting, which quickly solved my problem. I just set it to like 5 and it works consistently and quickly (instead of trying to flick it over and over.
