### ISSUE TITLE
Cannot use into docker

### ISSUE THREAD

**Issue by stich86** [OpenWonderLabs/homebridge-switchbot-ble#22]
Hi,

I want to use this plugin on official HB docker image, but the compilation fails because it doesn’t find “libudev.h”. I’ve tried to install manually the packaged “eudev-libs” but still not work.

Any hints?

Thanks

**Comment by stich86** [comment]
Sorry my fault, needed packages is “eudev-dev”, after issuing this correct packages the noble node  was compiled. Now I’ve to deal with host mode and root permission to access thru docker

**Comment by stich86** [comment]
need to reopen, i just go this error after configure curtain:

```
[12/6/2020, 2:45:15 PM] Error: Error relocating /homebridge/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE: symbol not found
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/homebridge/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/@abandonware/bluetooth-hci-socket/lib/native.js:6:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
```

**Comment by SwitchBot-Wonderlabs** [comment]
I'm sorry I don't know how to use Docker.

**Comment by antoniogermano** [comment]
According to the error message it seems you are missing some library or node module, maybe related to bluetooth. I haven't tried installing it on docker, I'm just trying to help.

Have you done this step?
```
sudo apt-get install bluetooth bluez libbluetooth-dev libudev-dev
```

What does your `Dockerfile` look like? Are you using volumes?
