### ISSUE TITLE
Error: Failed to discover services and characteristics: DISCONNECTED

### ISSUE THREAD

**Issue by shiienurm** [OpenWonderLabs/homebridge-switchbot-ble#26]
I'm having trouble with operating the curtains. Seems that bluetooth connection was made but I'm getting these errors. Sometimes it works sometimes not. 

```
[21/12/2020, 18:35:00] [SwitchBotPlatform] WoCurtain (mac address) was found.
[21/12/2020, 18:35:00] [SwitchBotPlatform] Curtain is moving...
[21/12/2020, 18:35:00] [SwitchBotPlatform] Error: Failed to discover services and characteristics: DISCONNECTED
    at SwitchbotDeviceWoCurtain._ondisconnect_internal (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/node-switchbot/lib/switchbot-device.js:161:16)
    at Peripheral.<anonymous> (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/node-switchbot/lib/switchbot-device.js:122:14)
    at Object.onceWrapper (events.js:421:28)
    at Peripheral.emit (events.js:315:20)
    at Noble.onDisconnect (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/@abandonware/noble/lib/noble.js:224:16)
    at NobleBindings.emit (events.js:315:20)
    at NobleBindings.onDisconnComplete (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:260:10)
    at Hci.emit (events.js:315:20)
    at Hci.onSocketData (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/@abandonware/noble/lib/hci-socket/hci.js:447:12)
    at BluetoothHciSocket.emit (events.js:315:20)
[21/12/2020, 18:35:00] [SwitchBotPlatform] Target position of Curtain failed to be set to: 100%
```

**Comment by SwitchBot-Wonderlabs** [comment]
@shiienurm , Sorry, there is no plan to support.
