### ISSUE TITLE
Error: Failed to discover services and characteristics: DISCONNECTED

### ISSUE THREAD

**Issue by shiienurm** [OpenWonderLabs/homebridge-switchbot-ble#27]
**Describe The Bug:**

I'm having trouble with operating the curtains. Seems that bluetooth connection was made but I'm getting these errors. Sometimes it works, sometimes not. 

**To Reproduce:**

**Expected behavior:**

I would like to open and close the curtains without need of taping the button multiple times.

**Logs:**
```
[21/12/2020, 18:35:00] [SwitchBotPlatform] WoCurtain (mac address) was found.
[21/12/2020, 18:35:00] [SwitchBotPlatform] Curtain is moving...
[21/12/2020, 18:35:00] [SwitchBotPlatform] Error: Failed to discover services and characteristics: DISCONNECTED
    at SwitchbotDeviceWoCurtain._ondisconnect_internal (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/node-switchbot/lib/switchbot-device.js:161:16)
    at Peripheral.<anonymous> (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/node-switchbot/lib/switchbot-device.js:122:14)
    at Object.onceWrapper (events.js:421:28)
    at Peripheral.emit (events.js:315:20)
    at Noble.onDisconnect (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/@abandonware/noble/lib/noble.js:224:16)
    at NobleBindings.emit (events.js:315:20)
    at NobleBindings.onDisconnComplete (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:260:10)
    at Hci.emit (events.js:315:20)
    at Hci.onSocketData (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/@abandonware/noble/lib/hci-socket/hci.js:447:12)
    at BluetoothHciSocket.emit (events.js:315:20)
[21/12/2020, 18:35:00] [SwitchBotPlatform] Target position of Curtain failed to be set to: 100%
```

**Homebridge Config:**

```json
 {
                    "type": "curtain",
                    "name": "Living Room Curtain",
                    "bleMac": "----",
                    "scanDuration": 4500,
                    "moveTime": 6000
                },
```

**Screenshots:**

**Device Model:**

SwitcBot Curtain 2x - Split curtains

# **Environment:**

- **Node.js Version**: v14.15.1
- **NPM Version**: 6.14.8
- **Homebridge Version**:  v1.1.7
- **Homebridge SwitchBot BLE Plugin Version**: v1.2.6
- **Homebridge Config UI X Plugin Version**: v4.36.0
- **Operating System**: Raspbian v1.0.15 - Raspberry Pi 4 Model B Rev 1.4

**Comment by donavanbecker** [comment]
@shiienurm can you try v1.2.7?

**Comment by shiienurm** [comment]
> @shiienurm can you try v1.2.7?

No luck, same issue. Not sure if it’s somehow linked to the issue, but the curtain closed position is not 100%. If I move it to certain open percentage in the SwitchBot app and try to control it via the Homebridg it works. 


```
[22/12/2020, 01:10:08] [SwitchBotPlatform] WoCurtain (mac address masked) was found.
[22/12/2020, 01:10:08] [SwitchBotPlatform] Curtain is moving...
[22/12/2020, 01:10:08] [SwitchBotPlatform] Error: Failed to discover services and characteristics: DISCONNECTED
    at SwitchbotDeviceWoCurtain._ondisconnect_internal (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/node-switchbot/lib/switchbot-device.js:161:16)
    at Peripheral.<anonymous> (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/node-switchbot/lib/switchbot-device.js:122:14)
    at Object.onceWrapper (events.js:421:28)
    at Peripheral.emit (events.js:315:20)
    at Noble.onDisconnect (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/@abandonware/noble/lib/noble.js:224:16)
    at NobleBindings.emit (events.js:315:20)
    at NobleBindings.onDisconnComplete (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:260:10)
    at Hci.emit (events.js:315:20)
    at Hci.onSocketData (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/@abandonware/noble/lib/hci-socket/hci.js:447:12)
    at BluetoothHciSocket.emit (events.js:315:20)
[22/12/2020, 01:10:08] [SwitchBotPlatform] Target position of Curtain failed to be set to: 100%
```

**Comment by donavanbecker** [comment]
Can you try v1.2.3?
