### ISSUE TITLE
Switchbot - Failed to discover services and characteristics: DISCONNECTED

### ISSUE THREAD

**Issue by daiiig** [OpenWonderLabs/homebridge-switchbot-ble#52]
**Describe Your Problem:**

occasionally after the plugin connects to a Switchbot it will generate this error and log instead of changing state.
Error: Failed to discover services and characteristics: DISCONNECTED

I installed the bluetooth abandonware/noble as directed, and it does work most of the time but still get these occasional failures and would like to fix this or at least have a way to give it a retry X times on failure.

Homebridge - v1.1.7
OS-Raspbian GNU/Linux Buster (10)
Node.js Version-v14.15.4
Npm Version-v6.14.9

**Logs:**

```
[08/01/2021, 02:00:07] [SwitchBotPlatform] Target state of Bot setting: OFF
[08/01/2021, 02:00:10] [SwitchBotPlatform] Scan done.
[08/01/2021, 02:00:10] [SwitchBotPlatform] WoHand (c5:57:f3:94:28:dc) was found.
[08/01/2021, 02:00:10] [SwitchBotPlatform] Bot is running...
[08/01/2021, 02:00:11] [SwitchBotPlatform] Error: Failed to discover services and characteristics: DISCONNECTED
    at SwitchbotDeviceWoHand._ondisconnect_internal (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/node-switchbot/lib/switchbot-device.js:161:16)
    at Peripheral.<anonymous> (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/node-switchbot/lib/switchbot-device.js:122:14)
    at Object.onceWrapper (events.js:421:28)
    at Peripheral.emit (events.js:315:20)
    at Noble.onDisconnect (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/@abandonware/noble/lib/noble.js:224:16)
    at NobleBindings.emit (events.js:315:20)
    at NobleBindings.onDisconnComplete (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:260:10)
    at Hci.emit (events.js:315:20)
    at Hci.onSocketData (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/@abandonware/noble/lib/hci-socket/hci.js:447:12)
    at BluetoothHciSocket.emit (events.js:315:20)
[08/01/2021, 02:00:11] [SwitchBotPlatform] Bot state failed to be set to: OFF
```

**Homebridge Config:**

```json
        {
            "devices": [
                {
                    "type": "bot",
                    "name": "mattress.bot",
                    "bleMac": "C5:57:F3:94:28:DC",
                    "scanDuration": 3000
                }
            ],
            "name": "SwitchBotPlatform",
            "platform": "SwitchBotPlatform"
        }

```

**Screenshots:**

**Comment by daiiig** [comment]
lol...why does my support request keep getting closed.  I followed the format on the support request link.

**Comment by monza258** [comment]
Hi, I got the same Error. 

```
[2021-2-26 10:50:46] [SwitchBotPlatform] Target position of Curtain was returned: 0%
[2021-2-26 10:51:08] [SwitchBotPlatform] Target position of Curtain setting: 100%
[2021-2-26 10:51:14] [SwitchBotPlatform] Scan done.
[2021-2-26 10:51:14] [SwitchBotPlatform] WoCurtain e1:c8:70:95:d2:ea
[2021-2-26 10:51:14] [SwitchBotPlatform] WoCurtain (e1:c8:70:95:d2:ea) was found.
[2021-2-26 10:51:14] [SwitchBotPlatform] Curtain is moving...
[2021-2-26 10:51:15] [SwitchBotPlatform] Error: Failed to discover services and characteristics: DISCONNECTED
    at SwitchbotDeviceWoCurtain._ondisconnect_internal (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/node-switchbot/lib/switchbot-device.js:161:16)
    at Peripheral.<anonymous> (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/node-switchbot/lib/switchbot-device.js:122:14)
    at Object.onceWrapper (events.js:421:28)
    at Peripheral.emit (events.js:315:20)
    at Noble.onDisconnect (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/@abandonware/noble/lib/noble.js:228:16)
    at NobleBindings.emit (events.js:315:20)
    at NobleBindings.onDisconnComplete (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:264:10)
    at Hci.emit (events.js:315:20)
    at Hci.onSocketData (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/@abandonware/noble/lib/hci-socket/hci.js:549:12)
    at BluetoothHciSocket.emit (events.js:315:20)
[2021-2-26 10:51:15] [SwitchBotPlatform] Target position of Curtain failed to be set to: 100%
[2021-2-26 10:51:33] [SwitchBotPlatform] Current position of Curtain was returned: 0%
[2021-2-26 10:51:33] [SwitchBotPlatform] The position state of Curtain was returned: 2
[2021-2-26 10:51:33] [SwitchBotPlatform] Target position of Curtain was returned: 0%
[2021-2-26 10:51:33] [SwitchBotPlatform] The position state of Curtain was returned: 2
```

**Comment by booruce** [comment]
I have this exact same issue.

**Comment by donavanbecker** [comment]
v1.3.0 is released
