### ISSUE TITLE
[SwitchBotPlatform] Error: No target device was found.

### ISSUE THREAD

**Issue by samsonrosen** [OpenWonderLabs/homebridge-switchbot-ble#7]
Hi, I'm having an issue with the plugin. It install successfully and looks like it launches but I'm getting the error below. I am using Mac OS X and I already use the zizi4n5 / homebridge-switchbot-for-mac which works great with my switchbot.

```
[08/11/2020, 14:26:00] [SwitchBotPlatform] Target position of the Curtain setting: 100%
objc[444]: Class BLEManager is implemented in both /usr/local/Cellar/node/12.4.0/lib/node_modules/homebridge-switchbot-for-mac/node_modules/@abandonware/noble/lib/mac/native/binding.node (0x105323b68) and /usr/local/Cellar/node/12.4.0/lib/node_modules/@switchbot/homebridge-switchbot-ble/node_modules/@abandonware/noble/lib/mac/native/binding.node (0x1053cdb78). One of the two will be used. Which one is undefined.
[08/11/2020, 14:26:05] [SwitchBotPlatform] Scan done.
[08/11/2020, 14:26:05] [SwitchBotPlatform] WoCurtain 
[08/11/2020, 14:26:05] [SwitchBotPlatform] Bedroom Curtain (da:61:c9:73:c5:72) was not found.
[08/11/2020, 14:26:05] [SwitchBotPlatform] Error: No target device was found.
    at /usr/local/Cellar/node/12.4.0/lib/node_modules/@switchbot/homebridge-switchbot-ble/dist/curtain-accessory.js:53:36
    at new Promise (<anonymous>:null:null)
    at /usr/local/Cellar/node/12.4.0/lib/node_modules/@switchbot/homebridge-switchbot-ble/dist/curtain-accessory.js:52:32

[08/11/2020, 14:26:05] [SwitchBotPlatform] Target position of the Curtain setting failed!
```

The config looks like this:

```
{
        "platform": "SwitchBotPlatform",
        "name": "SwitchBotPlatform",
        "devices": [
            {
                "type": "curtain",
                "name": "Bedroom Curtain",
                "bleMac": "DA:61:C9:73:C5:72",
                "scanDuration": 5000,
                "reverseDir": false
            }
        ]
    },

```
Thanks,

Sam

**Comment by SwitchBot-Wonderlabs** [comment]
#3
